<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-27T19:23:40 IST" name="Default suite" finished-at="2025-10-27T19:23:44 IST" duration-ms="4203">
    <groups>
    </groups>
    <test started-at="2025-10-27T19:23:40 IST" name="Default test" finished-at="2025-10-27T19:23:44 IST" duration-ms="4203">
      <class name="tests.ExtentReport4">
        <test-method is-config="true" signature="setExtent()[pri:0, instance:tests.ExtentReport4@7a8c8dcf]" started-at="2025-10-27T19:23:40 IST" name="setExtent" finished-at="2025-10-27T19:23:41 IST" duration-ms="347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.ExtentReport4@7a8c8dcf]" started-at="2025-10-27T19:23:41 IST" name="setUp" finished-at="2025-10-27T19:23:44 IST" duration-ms="3795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TitleTest()[pri:0, instance:tests.ExtentReport4@7a8c8dcf]" started-at="2025-10-27T19:23:44 IST" name="TitleTest" finished-at="2025-10-27T19:23:44 IST" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TitleTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:tests.ExtentReport4@7a8c8dcf]" started-at="2025-10-27T19:23:45 IST" name="afterSuite" finished-at="2025-10-27T19:23:45 IST" duration-ms="232" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentReports.flush()" because "this.extent" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.flush()" because "this.extent" is null
at tests.ExtentReport4.afterSuite(ExtentReport4.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:386)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- tests.ExtentReport4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
