<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Lenovo-KunalPC" failures="0" tests="5" name="tests.PIMTest" time="0.004" errors="1" timestamp="2025-08-17T15:39:52 IST" skipped="4">
  <testcase classname="tests.PIMTest" name="beforeMethod" time="0.004">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentReports.createTest(String)&quot; because &quot;this.extentReports&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.createTest(String)" because "this.extentReports" is null
at common.BaseSetup.beforeMethod(BaseSetup.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase classname="tests.PIMTest" name="verifyAddEmployee" time="0.000">
    <skipped/>
  </testcase> <!-- verifyAddEmployee -->
  <testcase classname="tests.PIMTest" name="verifySearchEmployee" time="0.000">
    <skipped/>
  </testcase> <!-- verifySearchEmployee -->
  <testcase classname="tests.PIMTest" name="verifyEditEmployee" time="0.000">
    <skipped/>
  </testcase> <!-- verifyEditEmployee -->
  <testcase classname="tests.PIMTest" name="verifyDeleteEmployee" time="0.000">
    <skipped/>
  </testcase> <!-- verifyDeleteEmployee -->
  <system-out>
    <![CDATA[Clicked successfully on element with XPath: //span[text()='Admin']
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnAdmin_20250817_153901.png (The system cannot find the path specified)
Clicked successfully on element with XPath: //button[contains(@class, 'oxd-button--secondary')]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnAddButton_20250817_153902.png (The system cannot find the path specified)
Clicked successfully on element with XPath: //input[@placeholder='Type for hints...']//preceding::i[1]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDselectUserRole_20250817_153903.png (The system cannot find the path specified)
Element not found with XPath: //div[@class='oxd-select-dropdown --position-bottom']//span[text()='Admin']
Entered value: a successfully into element with XPath: //input[@placeholder='Type for hints...']
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDselectEmployeeName_a_20250817_153903.png (The system cannot find the path specified)
Clicked successfully on element with XPath: //input[@placeholder='Type for hints...']//following::span[1]
Entered value: Akash Patil successfully into element with XPath: //label[text()='Username']//following::input[1]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDenterUsernameInSearchPanel_Akash Patil_20250817_153917.png (The system cannot find the path specified)
Clicked successfully on element with XPath: //label[text()='Username']//following::button[2]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnSearchButton_20250817_153917.png (The system cannot find the path specified)
Element not found with XPath: //div[text()='Actions']//following::button[2]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnUpdateButton_20250817_153928.png (The system cannot find the path specified)
Clicked successfully on element with XPath: //label[text()='Username']//following::i[1]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnBoxInUpdatePanel_20250817_153930.png (The system cannot find the path specified)
Element not found with XPath: //div[text()='Akash Patil']//following::button[1]
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnDeleteButton_20250817_153941.png (The system cannot find the path specified)
Element not found with XPath: //button[text()=' Yes, Delete ']
IOException occurred while saving the screenshot: C:\Users\ak200\OneDrive\Documents\workspace\SeleniumWDclickOnConfirmDeleteButton_20250817_153941.png (The system cannot find the path specified)]]>
  </system-out>
</testsuite> <!-- tests.PIMTest -->
